//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCore.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Location_en_gb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Location_en_gb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KCore.Content.Location_en-gb", typeof(Location_en_gb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error: {0}.
        /// </summary>
        internal static string M00001_1 {
            get {
                return ResourceManager.GetString("M00001_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to connect the {0} database..
        /// </summary>
        internal static string M00002_1 {
            get {
                return ResourceManager.GetString("M00002_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key is not correct format..
        /// </summary>
        internal static string M00003_0 {
            get {
                return ResourceManager.GetString("M00003_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value  is not correct format (request:{0}, value{1})..
        /// </summary>
        internal static string M00004_2 {
            get {
                return ResourceManager.GetString("M00004_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory is invalid. {0}.
        /// </summary>
        internal static string M00005_1 {
            get {
                return ResourceManager.GetString("M00005_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login expired, please login again..
        /// </summary>
        internal static string M00006_0 {
            get {
                return ResourceManager.GetString("M00006_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid the password key..
        /// </summary>
        internal static string M00007_0 {
            get {
                return ResourceManager.GetString("M00007_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible to decrypt the key {0}.
        /// </summary>
        internal static string M00008_1 {
            get {
                return ResourceManager.GetString("M00008_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is using the invalid security key..
        /// </summary>
        internal static string M00009_0 {
            get {
                return ResourceManager.GetString("M00009_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string M00010_1 {
            get {
                return ResourceManager.GetString("M00010_1", resourceCulture);
            }
        }
    }
}
